### ISSUE TITLE
Can't auth with couchdb using docker

### ISSUE THREAD

**Issue by fredguth** [jo/git-relax#1]
I am trying to use `docker compose up`

But the following error appears:
git-relax-git-server-1      | AH00526: Syntax error on line 19 of /etc/apache2/sites-enabled/000-default.conf:
git-relax-git-server-1      | Invalid command 'DefineExternalAuth', perhaps misspelled or defined by a module not included in the server configuration
git-relax-git-server-1      | Action '-DFOREGROUND' failed.
git-relax-git-server-1      | The Apache error log may have more information.

The aforementioned line in 000-default.conf is:
````
	DefineExternalAuth couchdb environment "/usr/local/bin/couchdb-auth http://localhost:5984"
`````

No idea on how to solve this.

Could you help?

**Comment by jo** [comment]
Hi @fredguth, thanks for your interest in git-relax!

The problem was probably due to incomplete setup, not installing `libapache2-mod-authnz-external`. On my maschine, docker setup halted on configuring tz and awaited user input. I have [fixed this by making it non-interactive and setting the timezone](https://github.com/jo/git-relax/commit/1454df4ba2c24012d568b203cb8881b9950bec29#diff-d6f6f5dc2a1767b9380bd3feaa2a5e950bf7f68dc40da8da6d5b059ff2e72f14R1-R3) in the Dockerfile. Also, to have this a little more futureproof, I pinned the Ubuntu version.

And I hardened the system a little, and made it log more verbose.

Please update and try again (fyi: I've renamed the branch to `main`)

**Comment by fredguth** [comment]
Thanks @jo, I had noticed it was the authnz module and had it installed by changing the Dockerfile, still I was struggling with the couchdb-worker (that is why I didn't create a PR).  This change is great news!  I am closing the issue.  Once again, thanks.

**Comment by fredguth** [comment]
Just to record... It is working perfectly! 😄

**Comment by jo** [comment]
cool!

**Comment by fredguth** [comment]
Where are the git repos saved in the server? I have looked for them at /srv/git and couldn't find.

**Comment by jo** [comment]
they're in `/var/www/git`, see eg here: https://github.com/jo/git-relax/blob/main/docker-compose.yml#L28
